### ISSUE TITLE
error: Cannot fetch frameworks_base from ssh://git@github.com/alphadroid-project/frameworks_baserepo sync errors

### ISSUE THREAD

**Issue by ghost** [AlphaDroid-Project/manifest#4]
error: Cannot fetch frameworks_base from ssh://git@github.com/alphadroid-project/frameworks_base
error: Cannot fetch packages_apps_Settings from ssh://git@github.com/alphadroid-project/packages_apps_Settings

**Comment by elpaablo** [comment]
Source is out-of-sync because of QPR2 update. It'll be in-sync again soon (I'm finishing the merge).

**Comment by elpaablo** [comment]
About ssh...You need a valid ssh key added to ssh-agent.
If you didn't do it yet, here's a help link: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.

**Comment by ghost** [comment]
out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/package-res.apk out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/proguard.options out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/R.txt out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/android/R.srcjar
rm -rf out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/aapt2/R && out/host/linux-x86/bin/aapt2 link -o out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/package-res.apk --private-symbols com.android.internal --no-auto-version --auto-add-overlay --enable-sparse-encoding --enable-compact-entries --manifest out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/manifest_fixer/AndroidManifest.xml -A frameworks/base/core/res/assets --min-sdk-version 34 --target-sdk-version 34 --version-code 34 --version-name  14 --product default -c en_US,en_US,af_ZA,am_ET,ar_EG,ar_XB,as_IN,az_AZ,be_BY,bg_BG,bn_BD,bs_BA,ca_ES,cs_CZ,da_DK,de_DE,el_GR,en_AU,en_CA,en_GB,en_IN,en_XA,es_ES,es_US,et_EE,eu_ES,fa_IR,fi_FI,fr_CA,fr_FR,gl_ES,gu_IN,hi_IN,hr_HR,hu_HU,hy_AM,in_ID,is_IS,it_IT,iw_IL,ja_JP,ka_GE,kk_KZ,km_KH,kn_IN,ko_KR,ky_KG,lo_LA,lt_LT,lv_LV,mk_MK,ml_IN,mn_MN,mr_IN,ms_MY,my_MM,nb_NO,ne_NP,nl_NL,or_IN,pa_IN,pl_PL,pt_BR,pt_PT,ro_RO,ru_RU,si_LK,sk_SK,sl_SI,sq_AL,sr_Latn_RS,sr_RS,sv_SE,sw_TZ,ta_IN,te_IN,th_TH,tl_PH,tr_TR,uk_UA,ur_PK,uz_UZ,vi_VN,zh_CN,zh_HK,zh_TW,zu_ZA,en_XC,ast_ES,gd_GB,cy_GB,fur_IT,normal --preferred-density xxhdpi --no-static-lib-packages --java out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/aapt2/R --proguard out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/proguard.options --output-text-symbols out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/R.txt @out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/aapt2/res.list -R @out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/aapt2/overlay.list&& out/host/linux-x86/bin/soong_zip -write_if_changed -jar -o out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/android/R.srcjar -C out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/aapt2/R -D out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/aapt2/R && rm -rf out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/gen/aapt2/R
frameworks/base/core/res/res/values/alpha_symbols.xml:74: error: no definition for declared symbol 'android:dimen/status_bar_padding_end'.
frameworks/base/core/res/res/values/alpha_symbols.xml:73: error: no definition for declared symbol 'android:dimen/status_bar_padding_start'.
frameworks/base/core/res/res/values/alpha_symbols.xml:75: error: no definition for declared symbol 'android:dimen/status_bar_padding_top'.
error: failed linking references.
08:03:06 ninja failed with: exit status 1

i know source is wip and here i am just justifying bugs or issues in source .
i hope you understood and tq for the response
