### ISSUE TITLE
error: cannot finish build bacon

### ISSUE THREAD

**Issue by Fabuxo** [AlphaDroid-Project/manifest#5]
[100% 199/199 1m1s remaining] build bacon
FAILED: bacon
/bin/bash -c "(mv -f  out/target/product/raphael/AlphaDroid-14.0-20240707-raphae
l-gapps-v2.2.zip ) && (prebuilts/build-tools/path/linux-x86/sha256sum out/target
/product/raphael/AlphaDroid-14.0-20240707-raphael-gapps-v2.2.zip | sed \"s|out/t
arget/product/raphael/||\" > out/target/product/raphael/AlphaDroid-14.0-20240707
-raphael-gapps-v2.2.zip.sha256sum ) && (./vendor/lineage/build/tools/createjson.
sh raphael out/target/product/raphael AlphaDroid-14.0-20240707-raphael-gapps-v2.
2.zip ) && (rm -rf out/target/product/raphael/obj/PACKAGING/target_files_interme
diates ) && (echo '' >&2 ) && (echo '_______ ______         ______          ____
____                _____ _________ ' >&2 ) && (echo '___    |___  /________ ___
  /_ ______ ____  __ \\______________ ___(_)______  / ' >&2 ) && (echo '__  /| |
__  / ___  __ \\__  __ \\_  __ \`/__  / / /__  ___/_  __ \\__  / _  __  /  ' >&2
 ) && (echo '_  ___ |_  /  __  /_/ /_  / / // /_/ / _  /_/ / _  /    / /_/ /_  /
  / /_/ /   ' >&2 ) && (echo '/_/  |_|/_/   _  .___/ /_/ /_/ \\__,_/  /_____/  /
_/     \\____/ /_/   \\__,_/    ' >&2 ) && (echo '              /_/             
                                                 ' >&2 ) && (echo '' >&2 ) && (e
cho '' >&2 ) && (echo \"Package Complete: out/target/product/raphael/AlphaDroid-
14.0-20240707-raphael-gapps-v2.2.zip\" >&2 )"
mv: Needs 2 arguments
09:16:01 ninja failed with: exit status 1

**Comment by Fabuxo** [comment]
Any help pls?
What´s with the mv: needs 2 arguments?

**Comment by czarsuperstar** [comment]
Try brunch raphael

**Comment by Fabuxo** [comment]
> Try brunch raphael

Same result

**Comment by mnirn** [comment]
late answer but check it again everything is okay now
